Add callout about human data and security
datacarpentry/cloud-genomics pull request #84
Opened 2019-04-25 07:31 UTC by nicjar

This is in response to https://github.com/datacarpentry/cloud-genomics/issues/73
Added a general paragraph about human data and the need to be aware of any ethical and legal requirements when working with human genomic data.

2019-05-01 14:15 UTC, ACharbonneau requested changes
Thanks for this! Could you change the two little grammar things and I'll merge it in.

2019-05-01 14:15 UTC, ACharbonneau commented on _episodes/04-which-cloud.md
> +> considerations that affects your choice of cloud resources to use. The terms of use, and/or
affect

2019-05-01 14:15 UTC, ACharbonneau commented on _episodes/04-which-cloud.md
> +> Also note that there might exist restrictions of use of cloud service providers that operate in other
restrictions for use

2019-05-02 05:56 UTC, nicjar commented
Changes done!

2019-05-05 23:52 UTC, merged